name: Merge Build Workflow

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      docker-registry:
        required: true
        type: string
      environment:
        required: true
        type: string
      jvm-memory-size:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build Application
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          JVM_MEMORY_SIZE: ${{ inputs.jvm-memory-size }}
        run: mvn clean package -DENVIRONMENT=$ENVIRONMENT -DJVM_MEMORY_SIZE=$JVM_MEMORY_SIZE

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.docker-registry }}/${{ inputs.service-name }}:latest .

      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login ${{ inputs.docker-registry }} -u "$DOCKER_USERNAME" --password-stdin
          docker push ${{ inputs.docker-registry }}/${{ inputs.service-name }}:latest
