name: PR Build Workflow

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      docker-registry:
        required: true
        type: string
      environment:
        required: true
        type: string
      jvm-memory-size:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set Up Maven and Java
        uses: s4u/setup-maven-action@v1.12.0
        with:
          maven-version: '3.8.4'  # Specify Maven version
          java-version: '17'      # Specify Java version

      - name: Build Application
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          JVM_MEMORY_SIZE: ${{ inputs.jvm-memory-size }}
        run: mvn clean package -DENVIRONMENT=$ENVIRONMENT -DJVM_MEMORY_SIZE=$JVM_MEMORY_SIZE

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.docker-registry }}/${{ inputs.service-name }}:latest .

      # Do not push the image in the PR build step
